// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmdkrgneouilsxhiaohl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZGtyZ25lb3VpbHN4aGlhb2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjU4NjEsImV4cCI6MjA3MDEwMTg2MX0.88oYjXd08GVeBliKexwoFipqWzHI4l30LPItxkjlciI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});